process.roles=broker,controller
node.id=1
controller.quorum.voters=1@localhost:9094

#   FORMAT:
#     listeners = listener_name://host_name:port
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092

listeners=PLAINTEXT://127.0.0.1:9092,SSL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094

advertised.listeners=PLAINTEXT://127.0.0.1:9092,SSL://server-ed54e252-6594-4bd9-9295-53e1293e4f68.ir-tbz-sh1.arvancompute.ir:9093

inter.broker.listener.name=PLAINTEXT #this name is just conventional. We can use anything
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL

ssl.keystore.location=/etc/kafka/secrets/kafka.server.keystore.jks
ssl.keystore.password=i4RMb7LzFtLSHbaHHHipu9Nfh1xkz+CJ
ssl.key.password=i4RMb7LzFtLSHbaHHHipu9Nfh1xkz+CJ #unlocks the private key entry itself, inside the keystore file, a second, inner layer of protection separate from the password that opens the keystore file.
ssl.truststore.location=/etc/kafka/secrets/kafka.server.truststore.jks
ssl.truststore.password=i4RMb7LzFtLSHbaHHHipu9Nfh1xkz+CJ

# Require client certs signed by your CA (mutual TLS), not just encryption
ssl.client.auth=required

ssl.enabled.protocols=TLSv1.2,TLSv1.3

#👆 This restricts the broker to only accept TLS versions 1.2 and 1.3 during the handshake,
# rejecting older, insecure versions (TLS 1.0, 1.1, SSLv3) that have known vulnerabilities.

log.dirs=/var/lib/kafka/data
metadata.log.dir=/var/lib/kafka/metadata
num.partitions=3

offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

log.retention.hours=168
log.segment.bytes=1073741824

# --- ACL demo additions ---
authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
ssl.principal.mapping.rules=RULE:^CN=(.*?)$/$1/,DEFAULT
super.users=User:admin;User:ANONYMOUS
