apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka-yaml
  labels:
    app: kafka
spec:
  clusterIP: None #🔴 pay attention to this line
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
      
---
# '---' is a YAML document separator
apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  namespace: kafka-yaml
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092


# kafka-headless (clusterIP: None):
# gives each Kafka pod its own stable DNS name (kafka-0.kafka-headless...),
# used by Kafka internally for controller quorum and broker identity.

# kafka-bootstrap, normal Service (auto-assigned clusterIP):
# gives clients one stable load-balanced entry point (kafka-bootstrap:9092) to reach the broker(s).
